// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Passowrd             string   `protobuf:"bytes,2,opt,name=passowrd,proto3" json:"passowrd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthReq) Reset()         { *m = AuthReq{} }
func (m *AuthReq) String() string { return proto.CompactTextString(m) }
func (*AuthReq) ProtoMessage()    {}
func (*AuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *AuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthReq.Unmarshal(m, b)
}
func (m *AuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthReq.Marshal(b, m, deterministic)
}
func (m *AuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthReq.Merge(m, src)
}
func (m *AuthReq) XXX_Size() int {
	return xxx_messageInfo_AuthReq.Size(m)
}
func (m *AuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthReq proto.InternalMessageInfo

func (m *AuthReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthReq) GetPassowrd() string {
	if m != nil {
		return m.Passowrd
	}
	return ""
}

type AuthResp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResp) Reset()         { *m = AuthResp{} }
func (m *AuthResp) String() string { return proto.CompactTextString(m) }
func (*AuthResp) ProtoMessage()    {}
func (*AuthResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *AuthResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResp.Unmarshal(m, b)
}
func (m *AuthResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResp.Marshal(b, m, deterministic)
}
func (m *AuthResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResp.Merge(m, src)
}
func (m *AuthResp) XXX_Size() int {
	return xxx_messageInfo_AuthResp.Size(m)
}
func (m *AuthResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResp proto.InternalMessageInfo

func (m *AuthResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AuthResp) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *AuthResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ValidateReq struct {
	TokenStr             string   `protobuf:"bytes,1,opt,name=tokenStr,proto3" json:"tokenStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateReq) Reset()         { *m = ValidateReq{} }
func (m *ValidateReq) String() string { return proto.CompactTextString(m) }
func (*ValidateReq) ProtoMessage()    {}
func (*ValidateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *ValidateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateReq.Unmarshal(m, b)
}
func (m *ValidateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateReq.Marshal(b, m, deterministic)
}
func (m *ValidateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateReq.Merge(m, src)
}
func (m *ValidateReq) XXX_Size() int {
	return xxx_messageInfo_ValidateReq.Size(m)
}
func (m *ValidateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateReq.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateReq proto.InternalMessageInfo

func (m *ValidateReq) GetTokenStr() string {
	if m != nil {
		return m.TokenStr
	}
	return ""
}

type ValidateResp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateResp) Reset()         { *m = ValidateResp{} }
func (m *ValidateResp) String() string { return proto.CompactTextString(m) }
func (*ValidateResp) ProtoMessage()    {}
func (*ValidateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *ValidateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResp.Unmarshal(m, b)
}
func (m *ValidateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResp.Marshal(b, m, deterministic)
}
func (m *ValidateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResp.Merge(m, src)
}
func (m *ValidateResp) XXX_Size() int {
	return xxx_messageInfo_ValidateResp.Size(m)
}
func (m *ValidateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResp.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResp proto.InternalMessageInfo

func (m *ValidateResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ValidateResp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ValidateResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SignUpReq struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpReq) Reset()         { *m = SignUpReq{} }
func (m *SignUpReq) String() string { return proto.CompactTextString(m) }
func (*SignUpReq) ProtoMessage()    {}
func (*SignUpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *SignUpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpReq.Unmarshal(m, b)
}
func (m *SignUpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpReq.Marshal(b, m, deterministic)
}
func (m *SignUpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpReq.Merge(m, src)
}
func (m *SignUpReq) XXX_Size() int {
	return xxx_messageInfo_SignUpReq.Size(m)
}
func (m *SignUpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpReq proto.InternalMessageInfo

func (m *SignUpReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *SignUpReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignUpReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignUpResp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResp) Reset()         { *m = SignUpResp{} }
func (m *SignUpResp) String() string { return proto.CompactTextString(m) }
func (*SignUpResp) ProtoMessage()    {}
func (*SignUpResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *SignUpResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResp.Unmarshal(m, b)
}
func (m *SignUpResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResp.Marshal(b, m, deterministic)
}
func (m *SignUpResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResp.Merge(m, src)
}
func (m *SignUpResp) XXX_Size() int {
	return xxx_messageInfo_SignUpResp.Size(m)
}
func (m *SignUpResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResp.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResp proto.InternalMessageInfo

func (m *SignUpResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SignUpResp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignUpResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthReq)(nil), "pb.AuthReq")
	proto.RegisterType((*AuthResp)(nil), "pb.AuthResp")
	proto.RegisterType((*ValidateReq)(nil), "pb.ValidateReq")
	proto.RegisterType((*ValidateResp)(nil), "pb.ValidateResp")
	proto.RegisterType((*SignUpReq)(nil), "pb.SignUpReq")
	proto.RegisterType((*SignUpResp)(nil), "pb.SignUpResp")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x55, 0x92, 0xaa, 0xa4, 0xd7, 0x02, 0xd5, 0x4d, 0x51, 0x26, 0x14, 0x06, 0x60, 0x20, 0x03,
	0x7c, 0x41, 0x25, 0x16, 0x16, 0x84, 0x52, 0x95, 0x15, 0x39, 0x8d, 0xd5, 0x46, 0xa5, 0xf6, 0x61,
	0x3b, 0xea, 0x07, 0xf0, 0xe3, 0xc8, 0x89, 0x9d, 0x06, 0x10, 0x4c, 0x6c, 0xf7, 0xde, 0xd9, 0xef,
	0xdd, 0x3d, 0x1b, 0x80, 0x35, 0x66, 0x9b, 0x93, 0x92, 0x46, 0x62, 0x48, 0x65, 0xb6, 0x80, 0x93,
	0x45, 0x63, 0xb6, 0x05, 0x7f, 0xc7, 0x14, 0xe2, 0x46, 0x73, 0x25, 0xd8, 0x9e, 0x27, 0xc1, 0x45,
	0x70, 0x3d, 0x29, 0x7a, 0x6c, 0x7b, 0xc4, 0xb4, 0x96, 0x07, 0x55, 0x25, 0x61, 0xd7, 0xf3, 0x38,
	0x7b, 0x80, 0xb8, 0x93, 0xd0, 0x84, 0x08, 0xa3, 0xb5, 0xac, 0xba, 0xfb, 0x51, 0xd1, 0xd6, 0x96,
	0xab, 0x98, 0x61, 0xee, 0x5e, 0x5b, 0xe3, 0x1c, 0xa2, 0xbd, 0xde, 0x24, 0x51, 0x4b, 0xd9, 0x32,
	0xbb, 0x81, 0xe9, 0x0b, 0x7b, 0xab, 0x2b, 0x66, 0xb8, 0x1b, 0xc6, 0xc8, 0x1d, 0x17, 0x4b, 0xa3,
	0xfc, 0x30, 0x1e, 0x67, 0xcf, 0x30, 0x3b, 0x1e, 0xfd, 0xc5, 0x74, 0xb8, 0x4c, 0xf8, 0x6d, 0x99,
	0x9f, 0xe6, 0xaf, 0x30, 0x59, 0xd6, 0x1b, 0xb1, 0x22, 0x67, 0x2d, 0xea, 0xf5, 0x6e, 0x98, 0x83,
	0xc7, 0x7f, 0xca, 0xba, 0x8c, 0x0e, 0x52, 0x55, 0x4e, 0xbb, 0xc7, 0xd9, 0x13, 0x80, 0x37, 0xf8,
	0x8f, 0x81, 0xef, 0x3e, 0x02, 0x18, 0xd9, 0xd0, 0xf1, 0x12, 0xc6, 0x56, 0xf8, 0x51, 0xe0, 0x34,
	0xa7, 0x32, 0x77, 0x6f, 0x99, 0xce, 0x8e, 0x40, 0x13, 0x5e, 0x75, 0x87, 0x56, 0x84, 0xa7, 0x96,
	0xef, 0x57, 0x4d, 0xcf, 0x86, 0x50, 0x13, 0xde, 0x42, 0xec, 0x93, 0xc5, 0x73, 0xdb, 0x1b, 0x3c,
	0x49, 0x3a, 0xff, 0x4a, 0x68, 0x2a, 0xc7, 0xed, 0x3f, 0xba, 0xff, 0x0c, 0x00, 0x00, 0xff, 0xff,
	0x3c, 0x50, 0xce, 0xed, 0x55, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	SignIn(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthResp, error)
	SignUp(ctx context.Context, in *SignUpReq, opts ...grpc.CallOption) (*SignUpResp, error)
	Validate(ctx context.Context, in *ValidateReq, opts ...grpc.CallOption) (*ValidateResp, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) SignIn(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthResp, error) {
	out := new(AuthResp)
	err := c.cc.Invoke(ctx, "/pb.Auth/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) SignUp(ctx context.Context, in *SignUpReq, opts ...grpc.CallOption) (*SignUpResp, error) {
	out := new(SignUpResp)
	err := c.cc.Invoke(ctx, "/pb.Auth/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Validate(ctx context.Context, in *ValidateReq, opts ...grpc.CallOption) (*ValidateResp, error) {
	out := new(ValidateResp)
	err := c.cc.Invoke(ctx, "/pb.Auth/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	SignIn(context.Context, *AuthReq) (*AuthResp, error)
	SignUp(context.Context, *SignUpReq) (*SignUpResp, error)
	Validate(context.Context, *ValidateReq) (*ValidateResp, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) SignIn(ctx context.Context, req *AuthReq) (*AuthResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedAuthServer) SignUp(ctx context.Context, req *SignUpReq) (*SignUpResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (*UnimplementedAuthServer) Validate(ctx context.Context, req *ValidateReq) (*ValidateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Auth/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).SignIn(ctx, req.(*AuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Auth/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).SignUp(ctx, req.(*SignUpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Auth/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Validate(ctx, req.(*ValidateReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _Auth_SignIn_Handler,
		},
		{
			MethodName: "SignUp",
			Handler:    _Auth_SignUp_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _Auth_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
